// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: plugin/v1/plugin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - vibecare.kernel.plugin.v1.PluginHost

/// Namespace containing generated types for the "vibecare.kernel.plugin.v1.PluginHost" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum VCKPluginHost {
    /// Service descriptor for the "vibecare.kernel.plugin.v1.PluginHost" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.plugin.v1.PluginHost")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Register" metadata.
        public enum Register {
            /// Request type for "Register".
            public typealias Input = VCKRegisterReq
            /// Response type for "Register".
            public typealias Output = VCKCoreMsg
            /// Descriptor for "Register".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.plugin.v1.PluginHost"),
                method: "Register"
            )
        }
        /// Namespace for "Publish" metadata.
        public enum Publish {
            /// Request type for "Publish".
            public typealias Input = VCKEvent
            /// Response type for "Publish".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "Publish".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.plugin.v1.PluginHost"),
                method: "Publish"
            )
        }
        /// Namespace for "Alert" metadata.
        public enum Alert {
            /// Request type for "Alert".
            public typealias Input = VCKAlertReq
            /// Response type for "Alert".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "Alert".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.plugin.v1.PluginHost"),
                method: "Alert"
            )
        }
        /// Descriptors for all methods in the "vibecare.kernel.plugin.v1.PluginHost" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Register.descriptor,
            Publish.descriptor,
            Alert.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "vibecare.kernel.plugin.v1.PluginHost" service.
    public static let vckPluginHost = GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.plugin.v1.PluginHost")
}

// MARK: vibecare.kernel.plugin.v1.PluginHost (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost {
    /// Streaming variant of the service protocol for the "vibecare.kernel.plugin.v1.PluginHost" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginHost is served by core over a unix socket. A plugin is ALWAYS the
    /// > gRPC client and NEVER a gRPC server (design D2) — core has no way to call
    /// > into a plugin over gRPC, by construction.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Register" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Register opens the single long-lived stream that does three jobs:
        /// > confirms registration (Ready), delivers subscribed bus events (Event),
        /// > and signals graceful shutdown (Shutdown).
        ///
        /// - Parameters:
        ///   - request: A streaming request of `VCKRegisterReq` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `VCKCoreMsg` messages.
        func register(
            request: GRPCCore.StreamingServerRequest<VCKRegisterReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<VCKCoreMsg>

        /// Handle the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `VCKEvent` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SwiftProtobuf.Google_Protobuf_Empty` messages.
        func publish(
            request: GRPCCore.StreamingServerRequest<VCKEvent>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SwiftProtobuf.Google_Protobuf_Empty>

        /// Handle the "Alert" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `VCKAlertReq` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SwiftProtobuf.Google_Protobuf_Empty` messages.
        func alert(
            request: GRPCCore.StreamingServerRequest<VCKAlertReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SwiftProtobuf.Google_Protobuf_Empty>
    }

    /// Service protocol for the "vibecare.kernel.plugin.v1.PluginHost" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginHost is served by core over a unix socket. A plugin is ALWAYS the
    /// > gRPC client and NEVER a gRPC server (design D2) — core has no way to call
    /// > into a plugin over gRPC, by construction.
    public protocol ServiceProtocol: VCKPluginHost.StreamingServiceProtocol {
        /// Handle the "Register" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Register opens the single long-lived stream that does three jobs:
        /// > confirms registration (Ready), delivers subscribed bus events (Event),
        /// > and signals graceful shutdown (Shutdown).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKRegisterReq` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `VCKCoreMsg` messages.
        func register(
            request: GRPCCore.ServerRequest<VCKRegisterReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<VCKCoreMsg>

        /// Handle the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKEvent` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        func publish(
            request: GRPCCore.ServerRequest<VCKEvent>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SwiftProtobuf.Google_Protobuf_Empty>

        /// Handle the "Alert" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKAlertReq` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        func alert(
            request: GRPCCore.ServerRequest<VCKAlertReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SwiftProtobuf.Google_Protobuf_Empty>
    }

    /// Simple service protocol for the "vibecare.kernel.plugin.v1.PluginHost" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginHost is served by core over a unix socket. A plugin is ALWAYS the
    /// > gRPC client and NEVER a gRPC server (design D2) — core has no way to call
    /// > into a plugin over gRPC, by construction.
    public protocol SimpleServiceProtocol: VCKPluginHost.ServiceProtocol {
        /// Handle the "Register" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Register opens the single long-lived stream that does three jobs:
        /// > confirms registration (Ready), delivers subscribed bus events (Event),
        /// > and signals graceful shutdown (Shutdown).
        ///
        /// - Parameters:
        ///   - request: A `VCKRegisterReq` message.
        ///   - response: A response stream of `VCKCoreMsg` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func register(
            request: VCKRegisterReq,
            response: GRPCCore.RPCWriter<VCKCoreMsg>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A `VCKEvent` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SwiftProtobuf.Google_Protobuf_Empty` to respond with.
        func publish(
            request: VCKEvent,
            context: GRPCCore.ServerContext
        ) async throws -> SwiftProtobuf.Google_Protobuf_Empty

        /// Handle the "Alert" method.
        ///
        /// - Parameters:
        ///   - request: A `VCKAlertReq` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SwiftProtobuf.Google_Protobuf_Empty` to respond with.
        func alert(
            request: VCKAlertReq,
            context: GRPCCore.ServerContext
        ) async throws -> SwiftProtobuf.Google_Protobuf_Empty
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: VCKPluginHost.Method.Register.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<VCKRegisterReq>(),
            serializer: GRPCProtobuf.ProtobufSerializer<VCKCoreMsg>(),
            handler: { request, context in
                try await self.register(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: VCKPluginHost.Method.Publish.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<VCKEvent>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            handler: { request, context in
                try await self.publish(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: VCKPluginHost.Method.Alert.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<VCKAlertReq>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            handler: { request, context in
                try await self.alert(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost.ServiceProtocol {
    public func register(
        request: GRPCCore.StreamingServerRequest<VCKRegisterReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<VCKCoreMsg> {
        let response = try await self.register(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func publish(
        request: GRPCCore.StreamingServerRequest<VCKEvent>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SwiftProtobuf.Google_Protobuf_Empty> {
        let response = try await self.publish(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func alert(
        request: GRPCCore.StreamingServerRequest<VCKAlertReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SwiftProtobuf.Google_Protobuf_Empty> {
        let response = try await self.alert(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost.SimpleServiceProtocol {
    public func register(
        request: GRPCCore.ServerRequest<VCKRegisterReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<VCKCoreMsg> {
        return GRPCCore.StreamingServerResponse<VCKCoreMsg>(
            metadata: [:],
            producer: { writer in
                try await self.register(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func publish(
        request: GRPCCore.ServerRequest<VCKEvent>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SwiftProtobuf.Google_Protobuf_Empty> {
        return GRPCCore.ServerResponse<SwiftProtobuf.Google_Protobuf_Empty>(
            message: try await self.publish(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func alert(
        request: GRPCCore.ServerRequest<VCKAlertReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SwiftProtobuf.Google_Protobuf_Empty> {
        return GRPCCore.ServerResponse<SwiftProtobuf.Google_Protobuf_Empty>(
            message: try await self.alert(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: vibecare.kernel.plugin.v1.PluginHost (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost {
    /// Generated client protocol for the "vibecare.kernel.plugin.v1.PluginHost" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginHost is served by core over a unix socket. A plugin is ALWAYS the
    /// > gRPC client and NEVER a gRPC server (design D2) — core has no way to call
    /// > into a plugin over gRPC, by construction.
    public protocol ClientProtocol: Sendable {
        /// Call the "Register" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Register opens the single long-lived stream that does three jobs:
        /// > confirms registration (Ready), delivers subscribed bus events (Event),
        /// > and signals graceful shutdown (Shutdown).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKRegisterReq` message.
        ///   - serializer: A serializer for `VCKRegisterReq` messages.
        ///   - deserializer: A deserializer for `VCKCoreMsg` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func register<Result>(
            request: GRPCCore.ClientRequest<VCKRegisterReq>,
            serializer: some GRPCCore.MessageSerializer<VCKRegisterReq>,
            deserializer: some GRPCCore.MessageDeserializer<VCKCoreMsg>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKCoreMsg>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKEvent` message.
        ///   - serializer: A serializer for `VCKEvent` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func publish<Result>(
            request: GRPCCore.ClientRequest<VCKEvent>,
            serializer: some GRPCCore.MessageSerializer<VCKEvent>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Alert" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKAlertReq` message.
        ///   - serializer: A serializer for `VCKAlertReq` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func alert<Result>(
            request: GRPCCore.ClientRequest<VCKAlertReq>,
            serializer: some GRPCCore.MessageSerializer<VCKAlertReq>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "vibecare.kernel.plugin.v1.PluginHost" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginHost is served by core over a unix socket. A plugin is ALWAYS the
    /// > gRPC client and NEVER a gRPC server (design D2) — core has no way to call
    /// > into a plugin over gRPC, by construction.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Register" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Register opens the single long-lived stream that does three jobs:
        /// > confirms registration (Ready), delivers subscribed bus events (Event),
        /// > and signals graceful shutdown (Shutdown).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKRegisterReq` message.
        ///   - serializer: A serializer for `VCKRegisterReq` messages.
        ///   - deserializer: A deserializer for `VCKCoreMsg` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func register<Result>(
            request: GRPCCore.ClientRequest<VCKRegisterReq>,
            serializer: some GRPCCore.MessageSerializer<VCKRegisterReq>,
            deserializer: some GRPCCore.MessageDeserializer<VCKCoreMsg>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKCoreMsg>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: VCKPluginHost.Method.Register.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKEvent` message.
        ///   - serializer: A serializer for `VCKEvent` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func publish<Result>(
            request: GRPCCore.ClientRequest<VCKEvent>,
            serializer: some GRPCCore.MessageSerializer<VCKEvent>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: VCKPluginHost.Method.Publish.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Alert" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `VCKAlertReq` message.
        ///   - serializer: A serializer for `VCKAlertReq` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func alert<Result>(
            request: GRPCCore.ClientRequest<VCKAlertReq>,
            serializer: some GRPCCore.MessageSerializer<VCKAlertReq>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: VCKPluginHost.Method.Alert.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost.ClientProtocol {
    /// Call the "Register" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Register opens the single long-lived stream that does three jobs:
    /// > confirms registration (Ready), delivers subscribed bus events (Event),
    /// > and signals graceful shutdown (Shutdown).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `VCKRegisterReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func register<Result>(
        request: GRPCCore.ClientRequest<VCKRegisterReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKCoreMsg>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.register(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<VCKRegisterReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<VCKCoreMsg>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Publish" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `VCKEvent` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func publish<Result>(
        request: GRPCCore.ClientRequest<VCKEvent>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.publish(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<VCKEvent>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Alert" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `VCKAlertReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func alert<Result>(
        request: GRPCCore.ClientRequest<VCKAlertReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.alert(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<VCKAlertReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKPluginHost.ClientProtocol {
    /// Call the "Register" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Register opens the single long-lived stream that does three jobs:
    /// > confirms registration (Ready), delivers subscribed bus events (Event),
    /// > and signals graceful shutdown (Shutdown).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func register<Result>(
        _ message: VCKRegisterReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKCoreMsg>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<VCKRegisterReq>(
            message: message,
            metadata: metadata
        )
        return try await self.register(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Publish" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func publish<Result>(
        _ message: VCKEvent,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<VCKEvent>(
            message: message,
            metadata: metadata
        )
        return try await self.publish(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Alert" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func alert<Result>(
        _ message: VCKAlertReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<VCKAlertReq>(
            message: message,
            metadata: metadata
        )
        return try await self.alert(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}