// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: topics/v1/vision.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Handedness is Vision's chirality call for one hand. UNSPECIFIED is what a
/// provider publishes when the model declined to choose — it is a real,
/// expected value, not a wire error.
public enum VCTHandedness: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case left // = 1
  case right // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .left
    case 2: self = .right
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .left: return 1
    case .right: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VCTHandedness] = [
    .unspecified,
    .left,
    .right,
  ]

}

/// Point is a normalized landmark in VIEWER SPACE.
///
///   origin top-left · x → right · y → DOWN · both normalized to 0..1
///
/// This is the frame as the user sees themselves in a mirrored selfie
/// preview, and it is NOT Vision's own convention (normalized, origin
/// bottom-left, y UP). The provider converts once, at the edge, and mirrors
/// BEFORE publishing. Consumers never mirror and never see a Vision-space
/// coordinate.
///
/// Mirroring is read from `connection.isVideoMirrored` per frame — never
/// cached, never inferred. The built-in Mac camera reports
/// `position = .unspecified`, so `automaticallyAdjustsVideoMirroring` never
/// engages and nothing arrives pre-mirrored; the provider flips the JPEG
/// preview and the landmark x together from that one source-of-truth flag.
///
/// Values may fall slightly outside 0..1 when a landmark is extrapolated past
/// the frame edge. Clamp if your math needs it; the provider does not.
public struct VCTPoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var x: Float = 0

  public var y: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Rect is a normalized bounding box in viewer space (see Point). `x`,`y` is
/// the TOP-LEFT corner, which is the corner nearest the origin in this
/// convention — not Vision's bottom-left.
public struct VCTRect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var x: Float = 0

  public var y: Float = 0

  public var w: Float = 0

  public var h: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Size is a pixel dimension, not a normalized one.
public struct VCTSize: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var w: UInt32 = 0

  public var h: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Header opens every vision payload so tiers can be joined.
///
/// A consumer needing face + hands + segmentation from the SAME frame joins
/// the three topics by `seq` and evaluates only on a complete set — a frame
/// whose segmentation was dropped for a slow subscriber is skipped, not
/// evaluated against stale data from an earlier frame.
public struct VCTHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Capture time, sampled when the frame left the camera — NOT when
  /// inference finished. Sampling after the model ran would fold inference
  /// latency into the timestamp and blow any downstream conformance window.
  public var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_ts = newValue}
  }
  /// Returns true if `ts` has been explicitly set.
  public var hasTs: Bool {return self._ts != nil}
  /// Clears the value of `ts`. Subsequent reads from it will return its default value.
  public mutating func clearTs() {self._ts = nil}

  /// Monotonic per provider, and SHARED by every topic derived from one
  /// frame — that sharing is what makes the join above possible. Gaps mean
  /// dropped frames (a slow subscriber, or a topic sampled at a lower rate
  /// than the capture session), never a protocol error.
  public var seq: UInt64 = 0

  /// Which camera produced this, when several exist. Stable for the life of
  /// a capture session; it changes when the user picks a different device.
  public var deviceID: String = String()

  /// Source pixel dimensions. Every coordinate in the payload is normalized
  /// against this, so a consumer that wants pixels multiplies by it — and a
  /// consumer that wants aspect-correct distances needs it, since normalized
  /// x and y are scaled by different amounts on a non-square frame.
  public var frame: VCTSize {
    get {return _frame ?? VCTSize()}
    set {_frame = newValue}
  }
  /// Returns true if `frame` has been explicitly set.
  public var hasFrame: Bool {return self._frame != nil}
  /// Clears the value of `frame`. Subsequent reads from it will return its default value.
  public mutating func clearFrame() {self._frame = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _frame: VCTSize? = nil
}

/// FaceFrame is published on `vision.face.v1`.
///
/// An empty `points` with a zero `bounds` is the valid "no face detected"
/// message. Only the highest-confidence face is published: multi-face is
/// deliberately deferred, and adding it later means a repeated field on a
/// `vision.face.v2` topic, not a break here.
public struct VCTFaceFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VCTHeader {
    get {return _header ?? VCTHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  /// Face bounding box in viewer space.
  public var bounds: VCTRect {
    get {return _bounds ?? VCTRect()}
    set {_bounds = newValue}
  }
  /// Returns true if `bounds` has been explicitly set.
  public var hasBounds: Bool {return self._bounds != nil}
  /// Clears the value of `bounds`. Subsequent reads from it will return its default value.
  public mutating func clearBounds() {self._bounds = nil}

  /// `VNFaceLandmarks2D.allPoints` for the 76-point constellation, already
  /// converted to viewer space, with the regions concatenated in Vision's own
  /// order:
  ///
  ///   faceContour · leftEye · rightEye · leftEyebrow · rightEyebrow ·
  ///   nose · noseCrest · medianLine · outerLips · innerLips ·
  ///   leftPupil · rightPupil
  ///
  /// The per-region point COUNTS are a property of Apple's constellation, not
  /// of this contract, and they differ between the 65- and 76-point ones. A
  /// consumer that indexes a specific region must therefore check
  /// `points.size()` first and must not hard-code an offset derived from a
  /// different constellation — the provider pins the offsets it publishes in
  /// its own tests, which is the only place they can be checked against a
  /// real model.
  ///
  /// Most consumers should not be in here at all: the derived geometry they
  /// actually want (eye aspect ratio, head pose) is already computed once on
  /// `vision.signals.v1`. Dropping to this tier is the documented escape
  /// hatch for a consumer whose math genuinely differs, not the default.
  public var points: [VCTPoint] = []

  /// Detector confidence, 0..1, for the face as a whole.
  public var confidence: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VCTHeader? = nil
  fileprivate var _bounds: VCTRect? = nil
}

/// Hand carries one detected hand's 21 joints.
public struct VCTHand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Exactly 21 joints, in this order — this ordering is NORMATIVE and is
  /// defined by this file, unlike the face constellation which is Apple's:
  ///
  ///    0  wrist
  ///    1  thumb CMC      2  thumb MP     3  thumb IP     4  thumb tip
  ///    5  index MCP      6  index PIP    7  index DIP    8  index tip
  ///    9  middle MCP    10  middle PIP  11  middle DIP  12  middle tip
  ///   13  ring MCP      14  ring PIP    15  ring DIP    16  ring tip
  ///   17  little MCP    18  little PIP  19  little DIP  20  little tip
  ///
  /// A joint the model could not locate is still published, at its last
  /// estimate, with a low entry in `joint_confidence` — the array is never
  /// short and never sparse, so index 8 is always the index fingertip.
  public var joints: [VCTPoint] = []

  public var handedness: VCTHandedness = .unspecified

  /// Confidence for the hand as a whole, 0..1.
  public var confidence: Float = 0

  /// Per-joint confidence, 0..1, parallel to `joints`. Either EMPTY — the
  /// provider does not report per-joint confidence — or exactly as long as
  /// `joints`; never any other length.
  ///
  /// Consumers doing fingertip math should gate on this when it is present
  /// rather than trusting every joint equally: a fingertip occluded behind
  /// the palm still has coordinates, and they are fiction. Empty means
  /// "unknown", NOT "zero confidence" — falling back to the frame-level
  /// `confidence` is the correct read, not discarding the hand.
  public var jointConfidence: [Float] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// HandsFrame is published on `vision.hands.v1`.
///
/// `hands` holds 0, 1 or 2 entries. Zero is the valid "no hands in frame"
/// message. Order is by descending `confidence`, not by handedness — a
/// consumer wanting "the left hand" must look at `Handedness`, never at
/// `hands[0]`.
public struct VCTHandsFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VCTHeader {
    get {return _header ?? VCTHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  public var hands: [VCTHand] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VCTHeader? = nil
}

/// Joint is one body-pose point with its own confidence. Body pose is far
/// more prone to per-joint dropouts than hand pose (occlusion by a desk, by
/// the frame edge), so confidence rides on the joint rather than only on the
/// frame.
public struct VCTJoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var point: VCTPoint {
    get {return _point ?? VCTPoint()}
    set {_point = newValue}
  }
  /// Returns true if `point` has been explicitly set.
  public var hasPoint: Bool {return self._point != nil}
  /// Clears the value of `point`. Subsequent reads from it will return its default value.
  public mutating func clearPoint() {self._point = nil}

  public var confidence: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _point: VCTPoint? = nil
}

/// BodyPoseFrame is published on `vision.body_pose.v1`.
///
/// An empty `joints` is the valid "no body detected" message.
public struct VCTBodyPoseFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VCTHeader {
    get {return _header ?? VCTHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  /// Exactly 19 joints when a body is detected, in this order — NORMATIVE,
  /// defined by this file:
  ///
  ///    0  nose
  ///    1  left eye        2  right eye
  ///    3  left ear        4  right ear
  ///    5  neck
  ///    6  left shoulder   7  right shoulder
  ///    8  left elbow      9  right elbow
  ///   10  left wrist     11  right wrist
  ///   12  root            (hip centre)
  ///   13  left hip       14  right hip
  ///   15  left knee      16  right knee
  ///   17  left ankle     18  right ankle
  ///
  /// "left" and "right" are the SUBJECT's left and right, which in viewer
  /// space appear on the mirrored side of the image from where a naive read
  /// would put them. Undetected joints are present with a low `confidence`,
  /// so index 6 is always the left shoulder.
  public var joints: [VCTJoint] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VCTHeader? = nil
}

/// SegmentationFrame is published on `vision.segmentation.v1`.
///
/// This replaces the polyline `scalp_line` that earlier designs put on the
/// face message: the shipping implementation produces a boolean grid, the two
/// are not interconvertible, and a 3072-cell grid never belonged inside a
/// face payload. Splitting topics by Vision request dissolves the conflict.
///
/// A frame with `w == 0 && h == 0` and an empty `mask` is the valid "no
/// person segmented" message.
public struct VCTSegmentationFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VCTHeader {
    get {return _header ?? VCTHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  /// Grid dimensions in cells, NOT pixels. The provider downsamples the
  /// person-segmentation buffer to a fixed grid (64x48 today) that is coarse
  /// enough to sample per frame and fine enough for a head silhouette.
  public var w: UInt32 = 0

  public var h: UInt32 = 0

  /// Row-major PACKED bitmask, one bit per cell, row 0 = TOP of the frame
  /// (viewer space — the same y-down convention as Point, so no flip).
  /// Columns are already mirrored to viewer space alongside every landmark.
  ///
  /// Bit for cell (col, row) is:
  ///
  ///   index = row * w + col
  ///   set   = (mask[index / 8] >> (7 - (index % 8))) & 1     // MSB first
  ///
  /// A set bit means "person". Length is ceil(w * h / 8) bytes; trailing bits
  /// in the final byte are zero and must be ignored. 64x48 packs to 384
  /// bytes, which is why this is a perfectly ordinary bus payload rather than
  /// something needing a side channel.
  public var mask: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VCTHeader? = nil
}

/// Signals is published on `vision.signals.v1` — derived geometry, computed
/// once by the provider so that every consumer does not re-derive it and
/// drift. Free to produce: pure math over landmarks another consumer already
/// paid for.
///
/// EVERY FIELD IS `optional`, AND ABSENT IS NOT ZERO. A field is absent when
/// the model that feeds it is not running — `ear_l` is missing whenever
/// nobody has asked for faces, and `shoulder_angle` is missing whenever
/// nobody has asked for body pose. A consumer that reads absent as 0.0 sees a
/// permanently closed eye and a perfectly level pair of shoulders. Check
/// presence before every read: `s.EarL != nil` in Go — `GetEarL()` returns 0
/// for both absent and zero and is the exact trap described above — and
/// `s.hasEarL` in Swift.
///
/// A signal only ships here if it is (1) a measurable property of the body
/// rather than a judgement about behaviour, (2) derivable from landmarks the
/// provider already computed for someone else, and (3) has a right answer on
/// a recorded clip so a test can fail. `is_blinking`, `is_slouching` and
/// `nail_biting` each fail (1) and (3), which is what keeps this tier from
/// rotting into a junk drawer.
public struct VCTSignals: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VCTHeader {
    get {return _header ?? VCTHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  /// Eye aspect ratio, per eye, dimensionless. Small means closed. Present
  /// only while `vision.face.v1`'s model is running. A consumer wanting a
  /// different EAR formula (6-point rather than 3-point) subscribes to
  /// `vision.face.v1` and derives its own — the points were already computed,
  /// so the lower rung costs the provider nothing.
  public var earL: Float {
    get {return _earL ?? 0}
    set {_earL = newValue}
  }
  /// Returns true if `earL` has been explicitly set.
  public var hasEarL: Bool {return self._earL != nil}
  /// Clears the value of `earL`. Subsequent reads from it will return its default value.
  public mutating func clearEarL() {self._earL = nil}

  public var earR: Float {
    get {return _earR ?? 0}
    set {_earR = newValue}
  }
  /// Returns true if `earR` has been explicitly set.
  public var hasEarR: Bool {return self._earR != nil}
  /// Clears the value of `earR`. Subsequent reads from it will return its default value.
  public mutating func clearEarR() {self._earR = nil}

  /// Head pose in DEGREES. Present only while the face model is running.
  public var yaw: Float {
    get {return _yaw ?? 0}
    set {_yaw = newValue}
  }
  /// Returns true if `yaw` has been explicitly set.
  public var hasYaw: Bool {return self._yaw != nil}
  /// Clears the value of `yaw`. Subsequent reads from it will return its default value.
  public mutating func clearYaw() {self._yaw = nil}

  public var pitch: Float {
    get {return _pitch ?? 0}
    set {_pitch = newValue}
  }
  /// Returns true if `pitch` has been explicitly set.
  public var hasPitch: Bool {return self._pitch != nil}
  /// Clears the value of `pitch`. Subsequent reads from it will return its default value.
  public mutating func clearPitch() {self._pitch = nil}

  public var roll: Float {
    get {return _roll ?? 0}
    set {_roll = newValue}
  }
  /// Returns true if `roll` has been explicitly set.
  public var hasRoll: Bool {return self._roll != nil}
  /// Clears the value of `roll`. Subsequent reads from it will return its default value.
  public mutating func clearRoll() {self._roll = nil}

  /// Shoulder line, degrees off horizontal. Present only while
  /// `vision.body_pose.v1`'s model is running.
  public var shoulderAngle: Float {
    get {return _shoulderAngle ?? 0}
    set {_shoulderAngle = newValue}
  }
  /// Returns true if `shoulderAngle` has been explicitly set.
  public var hasShoulderAngle: Bool {return self._shoulderAngle != nil}
  /// Clears the value of `shoulderAngle`. Subsequent reads from it will return its default value.
  public mutating func clearShoulderAngle() {self._shoulderAngle = nil}

  /// Forward-head distance, normalized against `Header.frame`. Present only
  /// while the body-pose model is running.
  public var neckForward: Float {
    get {return _neckForward ?? 0}
    set {_neckForward = newValue}
  }
  /// Returns true if `neckForward` has been explicitly set.
  public var hasNeckForward: Bool {return self._neckForward != nil}
  /// Clears the value of `neckForward`. Subsequent reads from it will return its default value.
  public mutating func clearNeckForward() {self._neckForward = nil}

  /// Minimum distance from any fingertip to the nose / mouth, normalized.
  /// Present only while BOTH the hand and face models are running, since
  /// either one missing makes the distance undefined rather than large.
  public var fingertipToNose: Float {
    get {return _fingertipToNose ?? 0}
    set {_fingertipToNose = newValue}
  }
  /// Returns true if `fingertipToNose` has been explicitly set.
  public var hasFingertipToNose: Bool {return self._fingertipToNose != nil}
  /// Clears the value of `fingertipToNose`. Subsequent reads from it will return its default value.
  public mutating func clearFingertipToNose() {self._fingertipToNose = nil}

  public var fingertipToMouth: Float {
    get {return _fingertipToMouth ?? 0}
    set {_fingertipToMouth = newValue}
  }
  /// Returns true if `fingertipToMouth` has been explicitly set.
  public var hasFingertipToMouth: Bool {return self._fingertipToMouth != nil}
  /// Clears the value of `fingertipToMouth`. Subsequent reads from it will return its default value.
  public mutating func clearFingertipToMouth() {self._fingertipToMouth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VCTHeader? = nil
  fileprivate var _earL: Float? = nil
  fileprivate var _earR: Float? = nil
  fileprivate var _yaw: Float? = nil
  fileprivate var _pitch: Float? = nil
  fileprivate var _roll: Float? = nil
  fileprivate var _shoulderAngle: Float? = nil
  fileprivate var _neckForward: Float? = nil
  fileprivate var _fingertipToNose: Float? = nil
  fileprivate var _fingertipToMouth: Float? = nil
}

/// Request is published on `vision.request.v1` BY CONSUMERS and subscribed by
/// the provider. It is the intent half of the control plane; the kernel's
/// demand refcount is the liveness half, and the provider runs the union of
/// live requests gated by demand.
///
/// Demand is truthful about liveness — zero subscribers closes the camera,
/// always, which is the privacy floor — but it cannot know INTENT: a user who
/// switches a detector off in that detector's own UI leaves the process up
/// and still subscribed, so demand stays at 1 and the LED stays on. This
/// message covers exactly that gap, with no kernel change: it is an ordinary
/// declared topic on both sides.
///
/// Desired state, latest-wins per `requester`. Re-assert on every reconnect
/// and on a heartbeat well inside the TTL (10s against a 30s TTL), because
/// events are ephemeral — there is no replay, and a request published while
/// the provider was restarting is simply gone.
///
/// EVERY CONSUMER MUST DECLARE `vision.request.v1` IN ITS MANIFEST'S
/// `publishes`. Publishing an undeclared topic is a logged error and a
/// dropped message, which here means the provider silently never runs the
/// model you need. Subscribing without requesting yields no events at all and
/// is indistinguishable from a broken bus, so the provider logs
/// `subscriber with no request` and surfaces it in `/api/state`.
///
/// This is not request/response tunnelled through pub/sub: nothing here
/// expects a reply, and if the provider is down, consumers publish into the
/// void and nothing breaks. It is a consumer broadcasting its own desired
/// state, which is what an event is.
public struct VCTRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The requesting plugin's id. SELF-ASSERTED and NOT AUTHENTICATED: the
  /// bus event carries no publisher identity, so this is what the requester
  /// claims to be. Acceptable because the channel cannot grant capability —
  /// it can only ask for work the demand floor still gates — but it is a real
  /// limitation, recorded here rather than discovered later.
  public var requester: String = String()

  /// Desired `vision.*` topics, by full topic name. An EMPTY LIST is
  /// meaningful: it retracts this requester's demand entirely, which is how a
  /// detector switched off in its own UI stops the models it was driving
  /// without exiting its process. Unknown topic names are ignored.
  public var topics: [String] = []

  /// Desired frame rate. The provider runs max() across live requesters per
  /// topic and caps the capture session at 30. 0 or absent means the default,
  /// 15. Per-topic rates are independent: a 2 fps posture consumer must not
  /// drag body-pose inference to 60 because a game wants faces fast.
  public var fps: UInt32 = 0

  /// Seconds this request stays live without re-assertion. 0 means the
  /// default, 30. The TTL is what stops a wedged consumer from pinning the
  /// camera open forever; a consumer that dies outright is handled sooner by
  /// the demand floor.
  public var ttlS: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibecare.topics.v1"

extension VCTHandedness: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HANDEDNESS_UNSPECIFIED\0\u{1}HANDEDNESS_LEFT\0\u{1}HANDEDNESS_RIGHT\0")
}

extension VCTPoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Point"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTPoint, rhs: VCTPoint) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTRect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Rect"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}w\0\u{1}h\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.w) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.h) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    if self.w.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.w, fieldNumber: 3)
    }
    if self.h.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.h, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTRect, rhs: VCTRect) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.w != rhs.w {return false}
    if lhs.h != rhs.h {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTSize: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Size"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}w\0\u{1}h\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.w) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.h) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.w != 0 {
      try visitor.visitSingularUInt32Field(value: self.w, fieldNumber: 1)
    }
    if self.h != 0 {
      try visitor.visitSingularUInt32Field(value: self.h, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTSize, rhs: VCTSize) -> Bool {
    if lhs.w != rhs.w {return false}
    if lhs.h != rhs.h {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Header"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ts\0\u{1}seq\0\u{3}device_id\0\u{1}frame\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._ts) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.seq) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._frame) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._ts {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.seq != 0 {
      try visitor.visitSingularUInt64Field(value: self.seq, fieldNumber: 2)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 3)
    }
    try { if let v = self._frame {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTHeader, rhs: VCTHeader) -> Bool {
    if lhs._ts != rhs._ts {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs._frame != rhs._frame {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTFaceFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FaceFrame"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}bounds\0\u{1}points\0\u{1}confidence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._bounds) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.points) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._bounds {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.points.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.points, fieldNumber: 3)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTFaceFrame, rhs: VCTFaceFrame) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs._bounds != rhs._bounds {return false}
    if lhs.points != rhs.points {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTHand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Hand"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}joints\0\u{1}handedness\0\u{1}confidence\0\u{3}joint_confidence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.joints) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.handedness) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      case 4: try { try decoder.decodeRepeatedFloatField(value: &self.jointConfidence) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.joints.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.joints, fieldNumber: 1)
    }
    if self.handedness != .unspecified {
      try visitor.visitSingularEnumField(value: self.handedness, fieldNumber: 2)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 3)
    }
    if !self.jointConfidence.isEmpty {
      try visitor.visitPackedFloatField(value: self.jointConfidence, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTHand, rhs: VCTHand) -> Bool {
    if lhs.joints != rhs.joints {return false}
    if lhs.handedness != rhs.handedness {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.jointConfidence != rhs.jointConfidence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTHandsFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandsFrame"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}hands\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.hands) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.hands.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.hands, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTHandsFrame, rhs: VCTHandsFrame) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.hands != rhs.hands {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTJoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Joint"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}point\0\u{1}confidence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._point) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._point {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTJoint, rhs: VCTJoint) -> Bool {
    if lhs._point != rhs._point {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTBodyPoseFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BodyPoseFrame"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}joints\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.joints) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.joints.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.joints, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTBodyPoseFrame, rhs: VCTBodyPoseFrame) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.joints != rhs.joints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTSegmentationFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SegmentationFrame"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}w\0\u{1}h\0\u{1}mask\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.w) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.h) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.mask) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.w != 0 {
      try visitor.visitSingularUInt32Field(value: self.w, fieldNumber: 2)
    }
    if self.h != 0 {
      try visitor.visitSingularUInt32Field(value: self.h, fieldNumber: 3)
    }
    if !self.mask.isEmpty {
      try visitor.visitSingularBytesField(value: self.mask, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTSegmentationFrame, rhs: VCTSegmentationFrame) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.w != rhs.w {return false}
    if lhs.h != rhs.h {return false}
    if lhs.mask != rhs.mask {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTSignals: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Signals"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{3}ear_l\0\u{3}ear_r\0\u{1}yaw\0\u{1}pitch\0\u{1}roll\0\u{3}shoulder_angle\0\u{3}neck_forward\0\u{3}fingertip_to_nose\0\u{3}fingertip_to_mouth\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._earL) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._earR) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self._yaw) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self._pitch) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self._roll) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self._shoulderAngle) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self._neckForward) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self._fingertipToNose) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self._fingertipToMouth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._earL {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._earR {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._yaw {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._pitch {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._roll {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._shoulderAngle {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._neckForward {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._fingertipToNose {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._fingertipToMouth {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTSignals, rhs: VCTSignals) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs._earL != rhs._earL {return false}
    if lhs._earR != rhs._earR {return false}
    if lhs._yaw != rhs._yaw {return false}
    if lhs._pitch != rhs._pitch {return false}
    if lhs._roll != rhs._roll {return false}
    if lhs._shoulderAngle != rhs._shoulderAngle {return false}
    if lhs._neckForward != rhs._neckForward {return false}
    if lhs._fingertipToNose != rhs._fingertipToNose {return false}
    if lhs._fingertipToMouth != rhs._fingertipToMouth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VCTRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requester\0\u{1}topics\0\u{1}fps\0\u{3}ttl_s\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requester) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.topics) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.fps) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.ttlS) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requester.isEmpty {
      try visitor.visitSingularStringField(value: self.requester, fieldNumber: 1)
    }
    if !self.topics.isEmpty {
      try visitor.visitRepeatedStringField(value: self.topics, fieldNumber: 2)
    }
    if self.fps != 0 {
      try visitor.visitSingularUInt32Field(value: self.fps, fieldNumber: 3)
    }
    if self.ttlS != 0 {
      try visitor.visitSingularUInt32Field(value: self.ttlS, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VCTRequest, rhs: VCTRequest) -> Bool {
    if lhs.requester != rhs.requester {return false}
    if lhs.topics != rhs.topics {return false}
    if lhs.fps != rhs.fps {return false}
    if lhs.ttlS != rhs.ttlS {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
