// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: client/v1/client.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - vibecare.kernel.client.v1.Shell

/// Namespace containing generated types for the "vibecare.kernel.client.v1.Shell" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum VCKShell {
    /// Service descriptor for the "vibecare.kernel.client.v1.Shell" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.client.v1.Shell")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Plugins" metadata.
        public enum Plugins {
            /// Request type for "Plugins".
            public typealias Input = SwiftProtobuf.Google_Protobuf_Empty
            /// Response type for "Plugins".
            public typealias Output = VCKPluginList
            /// Descriptor for "Plugins".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.client.v1.Shell"),
                method: "Plugins"
            )
        }
        /// Namespace for "Intents" metadata.
        public enum Intents {
            /// Request type for "Intents".
            public typealias Input = SwiftProtobuf.Google_Protobuf_Empty
            /// Response type for "Intents".
            public typealias Output = VCKUIIntent
            /// Descriptor for "Intents".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.client.v1.Shell"),
                method: "Intents"
            )
        }
        /// Descriptors for all methods in the "vibecare.kernel.client.v1.Shell" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Plugins.descriptor,
            Intents.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "vibecare.kernel.client.v1.Shell" service.
    public static let vckShell = GRPCCore.ServiceDescriptor(fullyQualifiedService: "vibecare.kernel.client.v1.Shell")
}

// MARK: vibecare.kernel.client.v1.Shell (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell {
    /// Streaming variant of the service protocol for the "vibecare.kernel.client.v1.Shell" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Shell is the entire client-facing plugin contract: two RPCs, frozen.
    /// > Clients contain no plugin-specific code — a client knows only "a URL",
    /// > never a schema.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Plugins" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `VCKPluginList` messages.
        func plugins(
            request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<VCKPluginList>

        /// Handle the "Intents" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `VCKUIIntent` messages.
        func intents(
            request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<VCKUIIntent>
    }

    /// Service protocol for the "vibecare.kernel.client.v1.Shell" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Shell is the entire client-facing plugin contract: two RPCs, frozen.
    /// > Clients contain no plugin-specific code — a client knows only "a URL",
    /// > never a schema.
    public protocol ServiceProtocol: VCKShell.StreamingServiceProtocol {
        /// Handle the "Plugins" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `VCKPluginList` messages.
        func plugins(
            request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<VCKPluginList>

        /// Handle the "Intents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `VCKUIIntent` messages.
        func intents(
            request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<VCKUIIntent>
    }

    /// Simple service protocol for the "vibecare.kernel.client.v1.Shell" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Shell is the entire client-facing plugin contract: two RPCs, frozen.
    /// > Clients contain no plugin-specific code — a client knows only "a URL",
    /// > never a schema.
    public protocol SimpleServiceProtocol: VCKShell.ServiceProtocol {
        /// Handle the "Plugins" method.
        ///
        /// - Parameters:
        ///   - request: A `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - response: A response stream of `VCKPluginList` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func plugins(
            request: SwiftProtobuf.Google_Protobuf_Empty,
            response: GRPCCore.RPCWriter<VCKPluginList>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "Intents" method.
        ///
        /// - Parameters:
        ///   - request: A `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - response: A response stream of `VCKUIIntent` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func intents(
            request: SwiftProtobuf.Google_Protobuf_Empty,
            response: GRPCCore.RPCWriter<VCKUIIntent>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: VCKShell.Method.Plugins.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<VCKPluginList>(),
            handler: { request, context in
                try await self.plugins(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: VCKShell.Method.Intents.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<VCKUIIntent>(),
            handler: { request, context in
                try await self.intents(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell.ServiceProtocol {
    public func plugins(
        request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<VCKPluginList> {
        let response = try await self.plugins(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func intents(
        request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<VCKUIIntent> {
        let response = try await self.intents(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell.SimpleServiceProtocol {
    public func plugins(
        request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<VCKPluginList> {
        return GRPCCore.StreamingServerResponse<VCKPluginList>(
            metadata: [:],
            producer: { writer in
                try await self.plugins(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func intents(
        request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<VCKUIIntent> {
        return GRPCCore.StreamingServerResponse<VCKUIIntent>(
            metadata: [:],
            producer: { writer in
                try await self.intents(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: vibecare.kernel.client.v1.Shell (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell {
    /// Generated client protocol for the "vibecare.kernel.client.v1.Shell" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Shell is the entire client-facing plugin contract: two RPCs, frozen.
    /// > Clients contain no plugin-specific code — a client knows only "a URL",
    /// > never a schema.
    public protocol ClientProtocol: Sendable {
        /// Call the "Plugins" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `VCKPluginList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func plugins<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<VCKPluginList>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKPluginList>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Intents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `VCKUIIntent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func intents<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<VCKUIIntent>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKUIIntent>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "vibecare.kernel.client.v1.Shell" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Shell is the entire client-facing plugin contract: two RPCs, frozen.
    /// > Clients contain no plugin-specific code — a client knows only "a URL",
    /// > never a schema.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Plugins" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `VCKPluginList` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func plugins<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<VCKPluginList>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKPluginList>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: VCKShell.Method.Plugins.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Intents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `VCKUIIntent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func intents<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<VCKUIIntent>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKUIIntent>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: VCKShell.Method.Intents.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell.ClientProtocol {
    /// Call the "Plugins" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func plugins<Result>(
        request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKPluginList>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.plugins(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<VCKPluginList>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Intents" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func intents<Result>(
        request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKUIIntent>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.intents(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<VCKUIIntent>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension VCKShell.ClientProtocol {
    /// Call the "Plugins" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func plugins<Result>(
        _ message: SwiftProtobuf.Google_Protobuf_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKPluginList>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.plugins(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Intents" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func intents<Result>(
        _ message: SwiftProtobuf.Google_Protobuf_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<VCKUIIntent>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.intents(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}