// swift-tools-version: 6.0
import PackageDescription

// The Swift plugin SDK, shared by every Swift plugin in this repo via a local
// path dependency (`.package(path: "../../sdk/swift/VCPluginSDK")`).
//
// It lived under plugins/vibecheck/Sources/ until vision, postures and
// blink-jump all needed it. Copying it a second time is exactly how the two
// disagreeing Package.resolved files already in this tree came to exist, so
// the dependency versions below are the ONE place they are declared —
// consumers must not add their own grpc-swift/swift-nio/swift-protobuf
// requirements. They get them transitively through VCPluginSDK/VCKStubs.
let package = Package(
  name: "VCPluginSDK",
  platforms: [.macOS(.v15)],
  products: [
    .library(name: "VCPluginSDK", targets: ["VCPluginSDK"]),
    // Exported separately because a plugin that only decodes bus payloads
    // (VCT* types from proto/topics/v1) needs the generated messages without
    // depending on the host machinery.
    .library(name: "VCKStubs", targets: ["VCKStubs"]),
  ],
  dependencies: [
    .package(url: "https://github.com/grpc/grpc-swift-2.git", from: "2.2.0"),
    .package(url: "https://github.com/grpc/grpc-swift-protobuf.git", from: "2.1.1"),
    .package(url: "https://github.com/grpc/grpc-swift-nio-transport.git", from: "2.3.1"),
    .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.31.0"),
    .package(url: "https://github.com/apple/swift-nio.git", from: "2.65.0"),
  ],
  targets: [
    // Generated by `scripts/generate_proto.sh -t plugin-swift`. Never edited
    // by hand — see Sources/VCKStubs and the README one level up.
    .target(
      name: "VCKStubs",
      dependencies: [
        .product(name: "GRPCCore", package: "grpc-swift-2"),
        .product(name: "GRPCProtobuf", package: "grpc-swift-protobuf"),
        .product(name: "SwiftProtobuf", package: "swift-protobuf"),
      ],
      path: "Sources/VCKStubs"
    ),
    .target(
      name: "VCPluginSDK",
      dependencies: [
        "VCKStubs",
        .product(name: "GRPCCore", package: "grpc-swift-2"),
        .product(name: "GRPCNIOTransportHTTP2Posix", package: "grpc-swift-nio-transport"),
        // For Google_Protobuf_Timestamp on plugin.v1.Event.ts.
        .product(name: "SwiftProtobuf", package: "swift-protobuf"),
        .product(name: "NIOCore", package: "swift-nio"),
        .product(name: "NIOPosix", package: "swift-nio"),
        .product(name: "NIOHTTP1", package: "swift-nio"),
      ],
      path: "Sources/VCPluginSDK"
    ),
    .testTarget(name: "VCPluginSDKTests", dependencies: ["VCPluginSDK"], path: "Tests/VCPluginSDKTests"),
  ]
)
